### ISSUE TITLE
Disable Roboto font import

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-material-styles#104]
It would be useful to provide a way to suppress the import of Roboto font while using Material theme (`using @Theme(value = Material.class`).

**Comment by buuzta** [comment]
The documentation (https://cdn-origin.vaadin.com/vaadin-themes/0.2.0/demo/material/) says "you need to import that yourself".
As Tarek mentioned just using Material theme leads to the link tag to https://fonts.googleapis.com.

Maybe it's a bug or the documentation needs an update.

**Comment by Haprog** [comment]
@buuzta That's a really old version of the documentation. It's for version 0.2.0 as you can see from the URL. In that old version Roboto was not yet imported by default. The current version of vaadin-material-styles is 1.3.2 and the latest documentation for it is here https://vaadin.com/docs/v14/themes/material/typography.html (which can also be found linked from https://vaadin.com/theming)

**Comment by web-padawan** [comment]
Currently, `vaadin-material-styles` 1.x includes Roboto by default. That can be only disabled with JS. 

We have an unreleased breaking change which disables import from Google Fonts.

**Comment by TatuLund** [comment]
Workaround for a Java developer.

Create file in src/main/resources folder

Say "disableroboto.js", add this line to the file

`window.polymerSkipLoadingFontRoboto = true;`

Then add `implements PageConfigurator` to your root layout if not already, and override `configurePage`

```
    @Override
    public void configurePage(InitialPageSettings settings) {
        settings.addInlineFromFile("./disableroboto.js", WrapMode.JAVASCRIPT);
    }
```
This ensures that that piece of JavaScript is executed at time of bootstraping of the page and before Roboto is attempted to be downloaded first time.

**Comment by thigg** [comment]
You can simplify this to:

```
    @Override
    public void configurePage(final InitialPageSettings settings) {
        settings.addInlineWithContents("window.polymerSkipLoadingFontRoboto = true;", InitialPageSettings.WrapMode.JAVASCRIPT);
    }
```

**Comment by thigg** [comment]
I got roboto font working again, by replacing replacing the statements that were guarded by `polymerSkipLoadingFontRoboto` .

To restore the functionality you can add the appended 2 files to your classpath (for me `src/main/resources`).
Put the Roboto fonts to your static resources (for me  `src/main/webapp`). I created them [here](https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=latin) using 300, regular, 500.

 Then you need to put this into your `configurePage` method as described in the posts above:

```java
settings.addInlineWithContents("window.polymerSkipLoadingFontRoboto = true;", InitialPageSettings.WrapMode.JAVASCRIPT);
settings.addInlineFromFile("./material-font-patch.css", InitialPageSettings.WrapMode.STYLESHEET);
settings.addInlineFromFile("./material-font-patch.js", InitialPageSettings.WrapMode.JAVASCRIPT);
```

`material-font-patch.css`
```css
/* roboto-300 - latin */
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 300;
    src: local(''),
    url('./fonts/roboto-v20-latin-300.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
    url('./fonts/roboto-v20-latin-300.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

/* roboto-regular - latin */
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 400;
    src: local(''),
    url('./fonts/roboto-v20-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
    url('./fonts/roboto-v20-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

/* roboto-500 - latin */
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 500;
    src: local(''),
    url('./fonts/roboto-v20-latin-500.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
    url('./fonts/roboto-v20-latin-500.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

```

`material-font-patch.js`

```js
const $_documentContainer = document.createElement('template');

$_documentContainer.innerHTML = `<custom-style>
  <style>
    html {
      /* Font family */
      --material-font-family: 'Roboto', sans-serif;

      /* Font sizes */
      --material-h1-font-size: 6rem;
      --material-h2-font-size: 3.75rem;
      --material-h3-font-size: 3rem;
      --material-h4-font-size: 2.125rem;
      --material-h5-font-size: 1.5rem;
      --material-h6-font-size: 1.25rem;
      --material-body-font-size: 1rem;
      --material-small-font-size: 0.875rem;
      --material-button-font-size: 0.875rem;
      --material-caption-font-size: 0.75rem;

      /* Icon size */
      --material-icon-font-size: 20px;
    }
  </style>
</custom-style><dom-module id="material-typography">
  <template>
    <style>
      body {
        font-family: var(--material-font-family);
        font-size: var(--material-body-font-size);
        line-height: 1.4;
        -webkit-text-size-adjust: 100%;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        color: inherit;
        line-height: 1.1;
        margin-top: 1.5em;
      }

      h1 {
        font-size: var(--material-h3-font-size);
        font-weight: 300;
        letter-spacing: -0.015em;
        margin-bottom: 1em;
        text-indent: -0.07em;
      }

      h2 {
        font-size: var(--material-h4-font-size);
        font-weight: 300;
        letter-spacing: -0.01em;
        margin-bottom: 0.75em;
        text-indent: -0.07em;
      }

      h3 {
        font-size: var(--material-h5-font-size);
        font-weight: 400;
        margin-bottom: 0.75em;
        text-indent: -0.05em;
      }

      h4 {
        font-size: var(--material-h6-font-size);
        font-weight: 400;
        letter-spacing: 0.01em;
        margin-bottom: 0.75em;
        text-indent: -0.05em;
      }

      h5 {
        font-size: var(--material-body-font-size);
        font-weight: 500;
        margin-bottom: 0.5em;
        text-indent: -0.025em;
      }

      h6 {
        font-size: var(--material-small-font-size);
        font-weight: 500;
        letter-spacing: 0.01em;
        margin-bottom: 0.25em;
        text-indent: -0.025em;
      }

      a,
      b,
      strong {
        font-weight: 500;
      }
    </style>
  </template>
</dom-module>`;

document.head.appendChild($_documentContainer.content);


```
