### ISSUE TITLE
Add icon button

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-material-styles#99]
Please add support for the `icon` theme for a button, similar to `ButtonVariant.LUMO_ICON`.

**Comment by mvysny** [comment]
Workaround is to have `material-button.css`:
```css
:host([theme ~= "icon"]) {
    min-width: 48px;
}

:host([theme ~= "icon"]) [part="prefix"] ::slotted(iron-icon) {
    margin-right: 0;
    margin-left: 0;
}
```

and `IconButton.java`:
```java
public class IconButton extends Button {
    public IconButton(@NotNull Component icon) {
        super(icon);
        addThemeName("icon");
    }
}
```

then include the css in the main layout:

```
@CssImport(value = "./styles/material-button.css", themeFor = "vaadin-button")
@Theme(Material.class)
public class MainLayout extends VerticalLayout implements RouterLayout {
}
```
